### ISSUE TITLE
Educational tips

### ISSUE THREAD

**Issue by mandily-p** [edehr/edehr#432]
Business requirement: Allow users to add helper text of their own, contextual to each assignment.

**Comment by bryan-gilbert** [comment]
Interesting idea. A user working in the EHR can add helper text to any EHR page element.  
Would need to carefully consider how to show this edit action. Will need to be able to delete too.  Could store the helper text in the ehr data record (seed or student).  Students could use this to ask for help from instructors.  Instructors could use this to help students.

Furthermore, could allow instructors to edit this content on a per student basis.

Parking this idea for the future because we have so many other things to do first but we don't want to lose this idea.

**Comment by bryan-gilbert** [comment]
close -- look in the parked issues to find
